(ns noumenon.introspect
  (:require [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [noumenon.agent :as agent]
            [noumenon.analyze :as analyze]
            [noumenon.benchmark :as bench]
            [noumenon.query :as query]
            [noumenon.util :refer [log!]]))

;; --- Loading ---

(defn load-meta-prompt []
  (:template (query/load-edn-resource "prompts/introspect.edn")))

(defn load-current-examples []
  (query/load-edn-resource "prompts/agent-examples.edn"))

(defn load-current-system-prompt []
  (:template (query/load-edn-resource "prompts/agent-system.edn")))

(defn- examples-resource-path []
  (str (.getFile (io/resource "prompts/agent-examples.edn"))))

(defn- system-prompt-resource-path []
  (str (.getFile (io/resource "prompts/agent-system.edn"))))

(defn load-history
  "Load improvement history from file. Returns [] if missing."
  [path]
  (let [f (io/file path)]
    (if (.exists f)
      (edn/read-string (slurp f))
      [])))

;; --- Meta-prompt assembly ---

(defn- format-scores
  "Format benchmark evaluation results as readable text."
  [results]
  (if (empty? results)
    "No baseline scores yet."
    (let [lines (mapv (fn [{:keys [id score]}]
                        (str "  " (name id) ": " (name score)))
                      results)]
      (str/join "\n" lines))))

(defn- format-history [history]
  (if (empty? history)
    "No prior iterations."
    (->> history
         (map-indexed
          (fn [i {:keys [target rationale outcome delta]}]
            (str "Iteration " (inc i) ": target=" (name target)
                 " outcome=" (name outcome)
                 (when delta (str " delta=" (format "%+.3f" delta)))
                 "\n  " rationale)))
         (str/join "\n\n"))))

(defn- format-query-catalog []
  (->> (query/list-query-names)
       (keep query/load-named-query)
       (map (fn [{:keys [name description]}]
              (str "  " name " — " description)))
       (str/join "\n")))

(defn build-meta-prompt
  "Assemble the meta-prompt for the optimizer LLM."
  [{:keys [system-prompt examples history baseline-results]}]
  (let [template      (load-meta-prompt)
        all-queries   (query/list-query-names)
        total-queries (count all-queries)]
    (-> template
        (str/replace "{{current-system-prompt}}" system-prompt)
        (str/replace "{{current-examples}}" (pr-str examples))
        (str/replace "{{example-count}}" (str (count examples)))
        (str/replace "{{total-queries}}" (str total-queries))
        (str/replace "{{all-queries}}" (format-query-catalog))
        (str/replace "{{baseline-scores}}" (format-scores baseline-results))
        (str/replace "{{history}}" (format-history history)))))

;; --- Proposal parsing ---

(defn parse-proposal
  "Parse the optimizer LLM's response into a proposal map."
  [text]
  (try
    (let [cleaned (analyze/strip-markdown-fences text)
          parsed  (edn/read-string cleaned)]
      (when (map? parsed)
        parsed))
    (catch Exception e
      (log! (str "introspect: parse error: " (.getMessage e)))
      nil)))

(defn- valid-query-names []
  (set (query/list-query-names)))

(defn validate-proposal
  "Validate a parsed proposal. Returns nil if valid, error string if not."
  [proposal]
  (let [{:keys [target modification rationale]} proposal]
    (cond
      (not (#{:examples :system-prompt} target))
      "Invalid :target — must be :examples or :system-prompt"

      (not (string? rationale))
      "Missing or invalid :rationale"

      (and (= :examples target)
           (not (vector? (:examples modification))))
      "For :examples target, :modification must contain {:examples [...]}"

      (and (= :examples target)
           (let [valid (valid-query-names)
                 names (:examples modification)]
             (some #(not (valid %)) names)))
      (str "Invalid query name(s) in :examples — valid: " (str/join ", " (sort (valid-query-names))))

      (and (= :system-prompt target)
           (not (string? (:template modification))))
      "For :system-prompt target, :modification must contain {:template \"...\"}"

      (and (= :system-prompt target)
           (let [tmpl (:template modification)]
             (not-every? #(str/includes? tmpl %)
                         ["{{repo-name}}" "{{schema}}" "{{rules}}" "{{examples}}"])))
      "System prompt template must preserve all {{placeholders}}: repo-name, schema, rules, examples"

      :else nil)))

;; --- Artifact I/O ---

(defn write-examples!
  "Write new agent-examples.edn to the classpath resource file."
  [examples]
  (let [path   (examples-resource-path)
        header (str ";;; Curated subset of named queries for the agent system prompt.\n"
                    ";;; Auto-generated by introspect at " (java.util.Date.) "\n")]
    (spit path (str header (pr-str examples) "\n"))))

(defn write-system-prompt!
  "Write new agent-system.edn to the classpath resource file."
  [template]
  (spit (system-prompt-resource-path)
        (pr-str {:template template})))

;; --- Agent-mode evaluation ---

(defn- score-kw->num [kw]
  (case kw :correct 1.0 :partial 0.5 :wrong 0.0 0.0))

(defn evaluate-agent!
  "Evaluate agent performance on deterministic benchmark questions.
   Runs each question through agent/ask, scores deterministically.
   Returns {:mean double :results [{:id kw :score kw :reasoning str}...] :usage map}."
  [db repo-name invoke-fn-factory]
  (let [targets   (bench/pick-benchmark-targets db)
        questions (->> (bench/load-questions)
                       (bench/resolve-question-params targets)
                       (filterv #(= :deterministic (:scoring %))))
        results   (mapv (fn [q]
                          (log! (str "  eval: " (name (:id q))))
                          (let [{:keys [answer]}
                                (agent/ask db (:question q)
                                           {:invoke-fn      (invoke-fn-factory)
                                            :repo-name      repo-name
                                            :max-iterations 6})
                                {:keys [score reasoning]}
                                (bench/deterministic-score q db (or answer ""))]
                            {:id (:id q) :score score :reasoning reasoning}))
                        questions)
        scores    (mapv (comp score-kw->num :score) results)]
    {:mean    (if (seq scores) (/ (reduce + scores) (count scores)) 0.0)
     :results results}))

;; --- History ---

(defn- ensure-parent! [path]
  (.mkdirs (.getParentFile (io/file path))))

(defn append-history!
  "Append an iteration record to the history file."
  [path record]
  (ensure-parent! path)
  (let [history (load-history path)]
    (spit path (pr-str (conj history record)))))

;; --- Iteration ---

(defn run-iteration!
  "Run a single introspect iteration.
   Returns {:outcome :improved/:reverted :record map}."
  [{:keys [db repo-name invoke-fn-factory optimizer-invoke-fn
           baseline history history-path]}]
  (let [;; Load current artifacts
        orig-examples (load-current-examples)
        orig-system   (load-current-system-prompt)
        ;; Build meta-prompt
        meta-prompt (build-meta-prompt
                     {:system-prompt    orig-system
                      :examples         orig-examples
                      :history          history
                      :baseline-results (:results baseline)})
        ;; Ask optimizer for proposal
        _           (log! "introspect: requesting proposal from optimizer...")
        response    (optimizer-invoke-fn
                     [{:role "user" :content meta-prompt}])
        proposal    (parse-proposal (:text response))]
    (if-not proposal
      (do (log! "introspect: failed to parse proposal, skipping")
          {:outcome :skipped
           :record  {:outcome :skipped :rationale "Parse failure"}})
      (if-let [err (validate-proposal proposal)]
        (do (log! (str "introspect: invalid proposal: " err))
            {:outcome :skipped
             :record  {:outcome :skipped :rationale (str "Validation: " err)}})
        (let [{:keys [target modification rationale]} proposal
              _ (log! (str "introspect: applying " (name target) " — " rationale))
              ;; Apply modification
              _ (case target
                  :examples      (write-examples! (:examples modification))
                  :system-prompt (write-system-prompt! (:template modification)))
              ;; Reset agent's cached prompts
              _ (agent/reset-prompt-cache!)
              ;; Evaluate
              _ (log! "introspect: evaluating...")
              eval-result (evaluate-agent! db repo-name invoke-fn-factory)
              new-mean    (:mean eval-result)
              base-mean   (:mean baseline)
              delta       (- new-mean base-mean)
              improved?   (> delta 0.001)]
          (if improved?
            (do (log! (str "introspect: IMPROVED " (format "%+.3f" delta)
                           " (" (format "%.3f" base-mean)
                           " -> " (format "%.3f" new-mean) ")"))
                (let [record {:timestamp    (str (java.util.Date.))
                              :target       target
                              :rationale    rationale
                              :baseline     base-mean
                              :result       new-mean
                              :delta        delta
                              :outcome      :improved
                              :modification modification}]
                  (append-history! history-path record)
                  {:outcome     :improved
                   :record      record
                   :eval-result eval-result}))
            (do (log! (str "introspect: reverted (delta=" (format "%+.3f" delta) ")"))
                ;; Restore originals
                (case target
                  :examples      (write-examples! orig-examples)
                  :system-prompt (write-system-prompt! orig-system))
                (agent/reset-prompt-cache!)
                (let [record {:timestamp    (str (java.util.Date.))
                              :target       target
                              :rationale    rationale
                              :baseline     base-mean
                              :result       new-mean
                              :delta        delta
                              :outcome      :reverted}]
                  (append-history! history-path record)
                  {:outcome :reverted
                   :record  record}))))))))

;; --- Main loop ---

(defn run-loop!
  "Run the introspect improvement loop.
   Returns {:iterations n :improvements n :final-score double :history vec}."
  [{:keys [db repo-name invoke-fn-factory optimizer-invoke-fn
           max-iterations max-hours max-cost history-path]
    :or   {max-iterations 10
           history-path   "data/introspect/history.edn"}}]
  (let [start-ms   (System/currentTimeMillis)
        max-ms     (when max-hours (* max-hours 3600000))
        history    (load-history history-path)
        ;; Initial baseline evaluation
        _          (log! "introspect: running baseline evaluation...")
        baseline   (evaluate-agent! db repo-name invoke-fn-factory)
        _          (log! (str "introspect: baseline mean=" (format "%.3f" (:mean baseline))))]
    (loop [i            0
           baseline     baseline
           history      history
           improvements 0
           total-cost   0.0]
      (let [elapsed-ms (- (System/currentTimeMillis) start-ms)
            time-up?   (and max-ms (> elapsed-ms max-ms))
            cost-up?   (and max-cost (> total-cost max-cost))]
        (cond
          (>= i max-iterations)
          (do (log! (str "introspect: reached max iterations (" max-iterations ")"))
              {:iterations i :improvements improvements
               :final-score (:mean baseline) :history history})

          time-up?
          (do (log! (str "introspect: time budget exhausted"))
              {:iterations i :improvements improvements
               :final-score (:mean baseline) :history history})

          cost-up?
          (do (log! (str "introspect: cost budget exhausted ($" (format "%.2f" total-cost) ")"))
              {:iterations i :improvements improvements
               :final-score (:mean baseline) :history history})

          :else
          (do (log! (str "\nintrospect: === Iteration " (inc i) "/" max-iterations " ==="))
              (let [{:keys [outcome eval-result record]}
                    (run-iteration!
                     {:db                 db
                      :repo-name          repo-name
                      :invoke-fn-factory  invoke-fn-factory
                      :optimizer-invoke-fn optimizer-invoke-fn
                      :baseline           baseline
                      :history            history
                      :history-path       history-path})
                    new-baseline (if (= :improved outcome)
                                   eval-result
                                   baseline)]
                (recur (inc i)
                       new-baseline
                       (conj history record)
                       (if (= :improved outcome) (inc improvements) improvements)
                       total-cost))))))))
